[package]
name = "based_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.20.2", features = ["full"]}
openal = "0.2.2"
rodio = "0.16.0"